segmentio/events

signal.go, signal_test.go
@f2prateek 
@yields 
Added a wrapper for a channel of signals that send events to a handler for each signal received. Here's an example of how it's intended to be used:
```go
sigchan := make(chan os.Signal, 1)
signal.Notify(sigchan, os.Interrupt)
// Sends all signals to the default logger's handler (log the event).
for sig := range events.Signal(sigchan, events.DefaultLogger.Handler) {
...
}
```
Please take a look and let me know if you'd like to see anything changed.
=> add events.Signal

README.md, log/doc.go, log/init.go, log/log.go, log/log_test.go, log/writer.go
@f2prateek 
@yields 
This is the Holy Grail of logging libraries, by simply importing the package, all messages logged by all packages using the standard `log` library will be re-routed to `events.DefaultLogger`. This means that there can be no more unformatted messages in the program's output, everything will be produced in the same format no matter what logging package is being used.
It also makes it possible to create a `*log.Logger` that, instead of writing to an `io.Writer`, will produce events to an `events.Handler`. This is really useful when using packages that have public APIs that depend on `log`, for example:
```go
import (
"net/http"
"github.com/segmentio/events"
"github.com/segmentio/events/log"
"labix.org/v2/mgo"
)
...
server := http.Server{
...
// ErrorLog is an …
```
=> add standard log package shim

.gitignore, httpevents/handler.go, httpevents/handler_test.go, netevents/conn.go, netevents/conn_test.go, netevents/dial.go, netevents/dial_test.go, netevents/handler.go, netevents/handler_test.go
@yields 
@f2prateek 
Here are implementations of other wrappers for automatically generating open/close events at the connection level.
I also tuned the `httpevents` handler log line so both the net and http events have the same prefixes when they come from the same connections (`local_address->remote_address`).
Please take a look and let me know if something should be changed.
=> add netevents

httpevents/handler.go, httpevents/request.go, httpevents/transport.go, httpevents/transport_test.go
@yields 
@f2prateek 
I added another wrapper for getting request logs on the client side, here's an example of how it can be used:
```go
// Wraps the default transport so it emits events on the default logger.
http.DefaultTransport = httpevents.NewTransport(nil, http.DefaultTransport)
```
The events have the same structure than the ones generated on the request handler, the only difference is the local address is `*` because it cannot be predicted (the transport abstracts away the connections it uses).
Please take a look and let me know if something should be changed.
=> Http transport

text/handler.go, text/handler_test.go
@f2prateek 
Follow up of our earlier conversation, add a way to control the output of the text handler that doesn't depend on how the events were generated.
=> add text.Handler.EnableArgs

text/init.go
@f2prateek 
The idea here is to make the default more useful by outputting the program name and PID in the text handler.
I'm working on a program that spawns sub-processes and having this is really valuable to differentiate which program logs are coming from.
=> add DefaultPrefix

ecslogs/handler.go, ecslogs/init.go
@f2prateek 
Follow up of #9, same idea with the ecslogs handler, getting the program and pid is good to differentiate where a log came from when there are multiple processes writing to the same output.
=> add program and pid to ecslogs handler

circle.yml, sigevents/doc.go, sigevents/init.go, sigevents/init_test.go
Follow up of our discussion on the stats package, here's the quick implementation of a package that when imported, adds handlers for SIGUSR1 and SIGUSR2 which enable or disable debug logs.
=> add sigevents package

ecslogs/init.go, log/log.go, terminal.go, terminal_bsd.go, terminal_linux.go, terminal_plan9.go, terminal_windows.go, text/init.go
Got tired of having to vendor the millions of files for golang.org/x/sys/unix in every project because github.com/golang/crypto/ssh/terminal depends on it...
=> drop terminal dependency

netevents/handler.go, netevents/listener.go, netevents/listener_test.go
For parity purposes with segmentio/stats and to make debugging easier, here's a decorator for `net.Listener` that adds logging.
Please take a look and let me know if something should be changed.
=> add netevents.NewListener

netevents/dial.go, netevents/handler.go, netevents/handler_test.go
This pull request drops the dependency on github.com/segmentio/netx, that package was mostly experimental stuff and I don't wanna maintain it, and contains tons of stuff that aren't used here.
=> drop github.com/segmentio/netx dependency

circle.yml, event_safe.go, event_unsafe.go, httpevents/request_unsafe.go, logger.go
Follow up of https://github.com/segmentio/events/pull/22 
Fixes the crash (mostly just disabling the unsafe optimization). I don't fully grasp why the GC complained here, I think it has to do with the fact that some heap allocated objects ended up with pointers to stack allocated values.
=> Fix unsafe crash

event_safe.go, event_test.go, event_unsafe.go, httpevents/request_unsafe.go, logger.go
I spotted an issue with a misuse of unsafe, this PR adds a test that reproduces pretty consistently the issue (except on the Circle CI run apparently), here's the trace:
```
$ CGO_ENABLED=0 GODEBUG=gccheckmark=1 GOTRACEBACK=crash GOGC=1 go test -v
=== RUN   TestEvent
=== RUN   TestEvent/Clone
--- PASS: TestEvent (0.00s)
--- PASS: TestEvent/Clone (0.00s)
=== RUN   TestArgs
=== RUN   TestArgs/Get
=== RUN   TestArgs/Map
--- PASS: TestArgs (0.00s)
--- PASS: TestArgs/Get (0.00s)
--- PASS: TestArgs/Map (0.00s)
=== RUN   TestUnsafe
runtime: pointer 0xc4209e5f90 to unallocated span idx=0x4f2 span.base()=0xc4206da000 span.limit=0xc4208da000 span.state=3
runtime: found in object at *(0xc420046600+0x18)
object=0xc420046600 k=0x6210023 s.base()=0xc420046000 s.limit=0xc420048000 s.sizeclass=17 …
```
=> test unsafe crash

ecslogs/handler_test.go, source.go, source_default.go, source_go17.go, source_test.go
Related resources:
- https://github.com/golang/go/issues/19426
- https://golang.org/pkg/runtime/#Func.FileLine
- https://golang.org/pkg/runtime/#Callers
> Note that since each slice entry pc[i] is a return program counter, looking up the file and line for pc[i] (for example, using (*Func).FileLine) will normally return the file and line number of the instruction immediately following the call. To easily look up file/line information for the call sequence, use Frames.
Go 1.7 introduced a new API to get accurate file/line numbers on the call stack, apparently some changes were made that causes `runtime.FileForFunc` to not be as straight-forward to use as it used to (I didn't really dig into the details).
For this program:
```go
package main
import (
"github.com/segmentio/events"
_ …
```
=> fix line number

eventstest/handler.go, eventstest/handler_test.go, httpevents/handler_test.go, httpevents/transport_test.go, log/log_test.go, netevents/handler_test.go
This includes a Handler implementation that can do the following:
1. Keep an internal copy of events it handles.
2. Make assertions on these events.
It makes assertions directly rather than leaving it upto clients to
simplify usage. From our usage this includes:
1. Ignoring unpredictable fields like source and time.
2. Printing error messages that pinpoint what went wrong.
Here's an example of the error message:
```
--- FAIL: TestHandler (0.00s)
handler.go:60: expected .Args to be [{from Han}] but got [{name
Luke} {from Han}]
handler.go:43: expected event {Message:Hello Luke! Source:
Args:[{Name:from Value:Han}] Time:0001-01-01 00:00:00 +0000 UTC
Debug:false} at index %!s(int=0) but got {Message:Hello Luke!
Source:github.com/segmentio/events/eventstest/handler_test.go:20
Args:[{Name:name …
```
=> Add eventstest package.

event.go, eventstest/handler.go, httpevents/handler.go, httpevents/handler_test.go, httpevents/header.go, httpevents/request.go, httpevents/request_safe.go, httpevents/request_test.go, httpevents/request_unsafe.go, httpevents/transport.go, httpevents/transport_test.go
This PR changes the http decorators to inject the request and response headers in the event arguments.
I'm having issues with the S3 API returning 501 due to unsupported headers on some requests, but because we're not recording the headers I have no way to know what was misconfigured, which is what motivated this change.
Please take a look and let me know if anything should be changed.
=> Capture http headers

signal.go, signal_test.go
This PR adds helper functions to test for errors caused by receiving signals. The intent is to make it simple for an application to identify those and prevent pointless logging of an error when it's actually expected behavior.
=> test signal errors

httpevents/handler_test.go, httpevents/header.go, httpevents/request.go
Currently, the httpevents logger logs all headers. This opens the possibility for logging credentials via the Authorization header. This PR removes the Authorization header to prevent situations of logging credentials to logs
=> Delete Authorization header from logs

ecslogs/init.go, log/init.go, sigevents/init.go, text/handler.go, text/init.go
When testing using `./...` syntax for your packages, events init
functions set in main packages may override init functions set in
testing packages.  This is undesirable for debugging testing packages.
This CR makes it so that import side effects do not happen.  All updates
must be explicit when tests are ran with the `test` tag.
e.g. `go test -tags testing ./...` will not call any init side effects
defined in `segmentio/events`.
https://stackoverflow.com/questions/14249217/how-do-i-know-im-running-within-go-test
=> init: add build flags for testing protection

httpevents/handler.go
Fix a typo detected by `misspell` in the comments.
=> Fix typo: "slienced" is a misspelling of "silenced"

httpevents/handler.go
Took me a bit to realize that some response codes are logged, while other are only logged in debug mode:
```go
// httpevents/request.go
switch {
case is4xx(r.status) || is5xx(r.status):
l.Log(bytesToStringNonEmpty(fmt), arg...)
default:
l.Debug(bytesToStringNonEmpty(fmt), arg...)
}
```
This PR just adds a small doc comment to clarify this.
=> Document which response codes are logged by `httpstats`

netevents/listener_test.go
On Mac, this flashes up a dialog about how the binary is listening on all interfaces.
=> netevents: don't bind to 0.0.0.0

logger.go, signal.go
The new log/slog package in the standard library is good enough for the use cases we initially wrote this library to solve. Please use it!
=> logger: deprecate the events logging functionality
